fail job if vulns present

diff --git a/.github/workflows/adventure02-expert-validate-changes.yaml b/.github/workflows/adventure02-expert-validate-changes.yaml
--- a/.github/workflows/adventure02-expert-validate-changes.yaml
+++ b/.github/workflows/adventure02-expert-validate-changes.yaml
@@ -182,4 +182,5 @@ jobs:
             });
 
       - name: 🚫 Fail on Blocking Vulnerabilities
-        run: echo "uhh... nevermind"
+        if: ${{ steps.count.outputs.critical != '0' || steps.count.outputs.high != '0' }}
+        run: echo "Critical or High Vulns found. Failing"; exit 1
